stage={scale:0,focus:{x:0,y:0,scale:0},scene:'menu'}
game={level:0,zone:0,edge:{x:0,y:0},tileSize:40,check:{x:0,y:0,type:0}}
physics={gravity:0.5,resistance:0.075,friction:0.025}
graphics={main:0,backgrounds:[],minor:[]}
transition={trigger:false,anim:0,scene:stage.scene,level:game.level,zone:game.zone,dead:false}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
entities={clouds:[],walls:[],enemies:[],players:[],particles:[]}
collision={incident:{x:0,y:0},calculate:{x:0,y:0}}
run={back:[],fore:[]}
a=0;b=0;c=0;d=0;_=0
la=0;lb=0;lc=0;ld=0